# app/config/security.yml
security:
    providers:
        db_provider:
            entity:
                class: AppBundle:Users
                property: Username
                
        anonymous_user:
            id: app.anonymous_user_provider
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false  
                
        secured_area:
            anonymous: ~
            guard:
                authenticators:
                    - app.token_authenticator
                    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manage, roles: ROLE_USER }                