services:
    # Entity services
    app.AccessTokensManager:
        class: AppBundle\Services\Entities\AccessTokensManager
        arguments: ['@doctrine.orm.entity_manager']   
        
    app.DocumentationManager:
        class: AppBundle\Services\Entities\DocumentationManager
        arguments: ['@doctrine.orm.entity_manager']       
       
    app.ForumCategoriesManager:
        class: AppBundle\Services\Entities\ForumCategoriesManager
        arguments: ['@doctrine.orm.entity_manager']   
        
    app.SiteModulesManager:
        class: AppBundle\Services\Entities\SiteModulesManager
        arguments: ['@doctrine.orm.entity_manager']   
        
    app.SitesManager:
        class: AppBundle\Services\Entities\SitesManager
        arguments: ['@doctrine.orm.entity_manager'] 
        
    app.UserRelationshipsManager:
        class: AppBundle\Services\Entities\UserRelationshipsManager
        arguments: ['@doctrine.orm.entity_manager']        
        
    app.UsersManager:
        class: AppBundle\Services\Entities\UsersManager
        arguments: ['@doctrine.orm.entity_manager', '@validator', '@app.SitesManager'] 
        
    # Generic services  
    app.AuthenticationManager:
        class: AppBundle\Services\AuthenticationManager
        arguments: ['@doctrine.orm.entity_manager', '@session']         
  
    app.LoggerManager:
        class: AppBundle\Services\LoggerManager
        arguments: ['@doctrine.orm.entity_manager']           
 
    app.SearchManager:
        class: AppBundle\Services\SearchManager
        arguments: ['@doctrine.orm.entity_manager']          
        
    app.SessionsManager:
        class: AppBundle\Services\SessionsManager
        arguments: ['@doctrine.orm.entity_manager']  
     
    # For generating hierarchical structures from doctrines array of entity objects
    app.TreeManager:
        class: AppBundle\Services\TreeManager 
        
    # Twig     
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
                 
    # Security             
    web.token_authenticator:
        class: AppBundle\Security\Web\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@session', '@app.UsersManager', '@app.SitesManager', '@router']
        
    api.token_authenticator:
        class: AppBundle\Security\Api\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@session', '@app.UsersManager', '@app.SitesManager', '@app.AccessTokensManager', '@router']
        
    # Security Voteers    
    app.UserVoter:
        class: AppBundle\Security\UserVoter
        arguments: ['@app.UsersManager', '@app.SitesManager']
        tags:
            - { name: security.voter }
         
    # Providers
    app.anonymous_user_provider:
        class: AppBundle\Security\AnonymousUserProvider