services:
    app.AuthenticationManager:
        class: AppBundle\Services\AuthenticationManager
        arguments: ['@doctrine.orm.entity_manager', '@session']       
    
    app.DocumentationManager:
        class: AppBundle\Services\DocumentationManager
        arguments: ['@doctrine.orm.entity_manager']   

    app.ErrorResponsesManager:
        class: AppBundle\Services\ErrorResponsesManager        
        
    app.ForumCategoriesManager:
        class: AppBundle\Services\ForumCategoriesManager
        arguments: ['@doctrine.orm.entity_manager']    
  
    app.LoggerManager:
        class: AppBundle\Services\LoggerManager
        arguments: ['@doctrine.orm.entity_manager']      
  
    app.SanitizeInputsManager:
        class: AppBundle\Services\SanitizeInputsManager
        arguments: ['@doctrine.orm.entity_manager']          
 
    app.SearchManager:
        class: AppBundle\Services\SearchManager
        arguments: ['@doctrine.orm.entity_manager']          
        
    app.SessionsManager:
        class: AppBundle\Services\SessionsManager
        arguments: ['@doctrine.orm.entity_manager']  
        
    app.SiteModulesManager:
        class: AppBundle\Services\SiteModulesManager
        arguments: ['@doctrine.orm.entity_manager']   
        
    app.SitesManager:
        class: AppBundle\Services\SitesManager
        arguments: ['@doctrine.orm.entity_manager']         

    app.UserRelationshipsManager:
        class: AppBundle\Services\UserRelationshipsManager
        arguments: ['@doctrine.orm.entity_manager']        
        
    app.UsersManager:
        class: AppBundle\Services\UsersManager
        arguments: ['@doctrine.orm.entity_manager', '@validator', '@app.SitesManager']
        
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
                 
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@session', '@app.UsersManager', '@router']
        
    app.UserVoter:
        class: AppBundle\Security\UserVoter
        tags:
            - { name: security.voter }
            
    app.anonymous_user_provider:
        class: AppBundle\Security\AnonymousUserProvider
